title: Bello Momoh Suleiman
logo: MyImage.jpeg
description: Data Analysts with 3 years of experience manipulating and interogating data, using analytical tools such as Power BI, Advance Excel, MS sql.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
