title: Bello Momoh Suleiman
logo: SuleimanBelloPic.jpg
description: Data Analyst with 2 years of experience in data manipulation, interrogation, and visualization. Skilled in Power BI for building insightful dashboards, Advanced Excel for complex analysis, and MS SQL for querying and managing relational databases. Proven ability to translate raw data into meaningful insights that support business decisions, improve processes, and drive performance across teams. Strong attention to detail and a passion for data-driven problem-solving.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
